# coding: utf-8

"""
    Honeywell Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class LocationGeoOccupancy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'within_fence': 'float',
        'outside_fence': 'float'
    }

    attribute_map = {
        'within_fence': 'withinFence',
        'outside_fence': 'outsideFence'
    }

    def __init__(self, within_fence=None, outside_fence=None):  # noqa: E501
        """LocationGeoOccupancy - a model defined in OpenAPI"""  # noqa: E501

        self._within_fence = None
        self._outside_fence = None
        self.discriminator = None

        if within_fence is not None:
            self.within_fence = within_fence
        if outside_fence is not None:
            self.outside_fence = outside_fence

    @property
    def within_fence(self):
        """Gets the within_fence of this LocationGeoOccupancy.  # noqa: E501


        :return: The within_fence of this LocationGeoOccupancy.  # noqa: E501
        :rtype: float
        """
        return self._within_fence

    @within_fence.setter
    def within_fence(self, within_fence):
        """Sets the within_fence of this LocationGeoOccupancy.


        :param within_fence: The within_fence of this LocationGeoOccupancy.  # noqa: E501
        :type: float
        """

        self._within_fence = within_fence

    @property
    def outside_fence(self):
        """Gets the outside_fence of this LocationGeoOccupancy.  # noqa: E501


        :return: The outside_fence of this LocationGeoOccupancy.  # noqa: E501
        :rtype: float
        """
        return self._outside_fence

    @outside_fence.setter
    def outside_fence(self, outside_fence):
        """Sets the outside_fence of this LocationGeoOccupancy.


        :param outside_fence: The outside_fence of this LocationGeoOccupancy.  # noqa: E501
        :type: float
        """

        self._outside_fence = outside_fence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LocationGeoOccupancy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
