# coding: utf-8

"""
    Honeywell Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ThermostatOperationStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'mode': 'str',
        'fan_request': 'bool',
        'circulation_fan_request': 'bool'
    }

    attribute_map = {
        'mode': 'mode',
        'fan_request': 'fanRequest',
        'circulation_fan_request': 'circulationFanRequest'
    }

    def __init__(self, mode=None, fan_request=None, circulation_fan_request=None):  # noqa: E501
        """ThermostatOperationStatus - a model defined in OpenAPI"""  # noqa: E501

        self._mode = None
        self._fan_request = None
        self._circulation_fan_request = None
        self.discriminator = None

        if mode is not None:
            self.mode = mode
        if fan_request is not None:
            self.fan_request = fan_request
        if circulation_fan_request is not None:
            self.circulation_fan_request = circulation_fan_request

    @property
    def mode(self):
        """Gets the mode of this ThermostatOperationStatus.  # noqa: E501


        :return: The mode of this ThermostatOperationStatus.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this ThermostatOperationStatus.


        :param mode: The mode of this ThermostatOperationStatus.  # noqa: E501
        :type: str
        """

        self._mode = mode

    @property
    def fan_request(self):
        """Gets the fan_request of this ThermostatOperationStatus.  # noqa: E501


        :return: The fan_request of this ThermostatOperationStatus.  # noqa: E501
        :rtype: bool
        """
        return self._fan_request

    @fan_request.setter
    def fan_request(self, fan_request):
        """Sets the fan_request of this ThermostatOperationStatus.


        :param fan_request: The fan_request of this ThermostatOperationStatus.  # noqa: E501
        :type: bool
        """

        self._fan_request = fan_request

    @property
    def circulation_fan_request(self):
        """Gets the circulation_fan_request of this ThermostatOperationStatus.  # noqa: E501


        :return: The circulation_fan_request of this ThermostatOperationStatus.  # noqa: E501
        :rtype: bool
        """
        return self._circulation_fan_request

    @circulation_fan_request.setter
    def circulation_fan_request(self, circulation_fan_request):
        """Sets the circulation_fan_request of this ThermostatOperationStatus.


        :param circulation_fan_request: The circulation_fan_request of this ThermostatOperationStatus.  # noqa: E501
        :type: bool
        """

        self._circulation_fan_request = circulation_fan_request

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ThermostatOperationStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
