# coding: utf-8

"""
    Honeywell Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ThermostatChangeableValues(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'mode': 'str',
        'auto_changeover_active': 'bool',
        'emergency_heat_active': 'bool',
        'heat_setpoint': 'float',
        'cool_setpoint': 'float',
        'thermostat_setpoint_status': 'str',
        'next_period_time': 'str',
        'end_heat_setpoint': 'float',
        'end_cool_setpoint': 'float',
        'heat_cool_mode': 'str'
    }

    attribute_map = {
        'mode': 'mode',
        'auto_changeover_active': 'autoChangeoverActive',
        'emergency_heat_active': 'emergencyHeatActive',
        'heat_setpoint': 'heatSetpoint',
        'cool_setpoint': 'coolSetpoint',
        'thermostat_setpoint_status': 'thermostatSetpointStatus',
        'next_period_time': 'nextPeriodTime',
        'end_heat_setpoint': 'endHeatSetpoint',
        'end_cool_setpoint': 'endCoolSetpoint',
        'heat_cool_mode': 'heatCoolMode'
    }

    def __init__(self, mode=None, auto_changeover_active=None, emergency_heat_active=None, heat_setpoint=None, cool_setpoint=None, thermostat_setpoint_status=None, next_period_time=None, end_heat_setpoint=None, end_cool_setpoint=None, heat_cool_mode=None):  # noqa: E501
        """ThermostatChangeableValues - a model defined in OpenAPI"""  # noqa: E501

        self._mode = None
        self._auto_changeover_active = None
        self._emergency_heat_active = None
        self._heat_setpoint = None
        self._cool_setpoint = None
        self._thermostat_setpoint_status = None
        self._next_period_time = None
        self._end_heat_setpoint = None
        self._end_cool_setpoint = None
        self._heat_cool_mode = None
        self.discriminator = None

        if mode is not None:
            self.mode = mode
        if auto_changeover_active is not None:
            self.auto_changeover_active = auto_changeover_active
        if emergency_heat_active is not None:
            self.emergency_heat_active = emergency_heat_active
        if heat_setpoint is not None:
            self.heat_setpoint = heat_setpoint
        if cool_setpoint is not None:
            self.cool_setpoint = cool_setpoint
        if thermostat_setpoint_status is not None:
            self.thermostat_setpoint_status = thermostat_setpoint_status
        if next_period_time is not None:
            self.next_period_time = next_period_time
        if end_heat_setpoint is not None:
            self.end_heat_setpoint = end_heat_setpoint
        if end_cool_setpoint is not None:
            self.end_cool_setpoint = end_cool_setpoint
        if heat_cool_mode is not None:
            self.heat_cool_mode = heat_cool_mode

    @property
    def mode(self):
        """Gets the mode of this ThermostatChangeableValues.  # noqa: E501


        :return: The mode of this ThermostatChangeableValues.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this ThermostatChangeableValues.


        :param mode: The mode of this ThermostatChangeableValues.  # noqa: E501
        :type: str
        """

        self._mode = mode

    @property
    def auto_changeover_active(self):
        """Gets the auto_changeover_active of this ThermostatChangeableValues.  # noqa: E501


        :return: The auto_changeover_active of this ThermostatChangeableValues.  # noqa: E501
        :rtype: bool
        """
        return self._auto_changeover_active

    @auto_changeover_active.setter
    def auto_changeover_active(self, auto_changeover_active):
        """Sets the auto_changeover_active of this ThermostatChangeableValues.


        :param auto_changeover_active: The auto_changeover_active of this ThermostatChangeableValues.  # noqa: E501
        :type: bool
        """

        self._auto_changeover_active = auto_changeover_active

    @property
    def emergency_heat_active(self):
        """Gets the emergency_heat_active of this ThermostatChangeableValues.  # noqa: E501


        :return: The emergency_heat_active of this ThermostatChangeableValues.  # noqa: E501
        :rtype: bool
        """
        return self._emergency_heat_active

    @emergency_heat_active.setter
    def emergency_heat_active(self, emergency_heat_active):
        """Sets the emergency_heat_active of this ThermostatChangeableValues.


        :param emergency_heat_active: The emergency_heat_active of this ThermostatChangeableValues.  # noqa: E501
        :type: bool
        """

        self._emergency_heat_active = emergency_heat_active

    @property
    def heat_setpoint(self):
        """Gets the heat_setpoint of this ThermostatChangeableValues.  # noqa: E501


        :return: The heat_setpoint of this ThermostatChangeableValues.  # noqa: E501
        :rtype: float
        """
        return self._heat_setpoint

    @heat_setpoint.setter
    def heat_setpoint(self, heat_setpoint):
        """Sets the heat_setpoint of this ThermostatChangeableValues.


        :param heat_setpoint: The heat_setpoint of this ThermostatChangeableValues.  # noqa: E501
        :type: float
        """

        self._heat_setpoint = heat_setpoint

    @property
    def cool_setpoint(self):
        """Gets the cool_setpoint of this ThermostatChangeableValues.  # noqa: E501


        :return: The cool_setpoint of this ThermostatChangeableValues.  # noqa: E501
        :rtype: float
        """
        return self._cool_setpoint

    @cool_setpoint.setter
    def cool_setpoint(self, cool_setpoint):
        """Sets the cool_setpoint of this ThermostatChangeableValues.


        :param cool_setpoint: The cool_setpoint of this ThermostatChangeableValues.  # noqa: E501
        :type: float
        """

        self._cool_setpoint = cool_setpoint

    @property
    def thermostat_setpoint_status(self):
        """Gets the thermostat_setpoint_status of this ThermostatChangeableValues.  # noqa: E501


        :return: The thermostat_setpoint_status of this ThermostatChangeableValues.  # noqa: E501
        :rtype: str
        """
        return self._thermostat_setpoint_status

    @thermostat_setpoint_status.setter
    def thermostat_setpoint_status(self, thermostat_setpoint_status):
        """Sets the thermostat_setpoint_status of this ThermostatChangeableValues.


        :param thermostat_setpoint_status: The thermostat_setpoint_status of this ThermostatChangeableValues.  # noqa: E501
        :type: str
        """

        self._thermostat_setpoint_status = thermostat_setpoint_status

    @property
    def next_period_time(self):
        """Gets the next_period_time of this ThermostatChangeableValues.  # noqa: E501


        :return: The next_period_time of this ThermostatChangeableValues.  # noqa: E501
        :rtype: str
        """
        return self._next_period_time

    @next_period_time.setter
    def next_period_time(self, next_period_time):
        """Sets the next_period_time of this ThermostatChangeableValues.


        :param next_period_time: The next_period_time of this ThermostatChangeableValues.  # noqa: E501
        :type: str
        """

        self._next_period_time = next_period_time

    @property
    def end_heat_setpoint(self):
        """Gets the end_heat_setpoint of this ThermostatChangeableValues.  # noqa: E501


        :return: The end_heat_setpoint of this ThermostatChangeableValues.  # noqa: E501
        :rtype: float
        """
        return self._end_heat_setpoint

    @end_heat_setpoint.setter
    def end_heat_setpoint(self, end_heat_setpoint):
        """Sets the end_heat_setpoint of this ThermostatChangeableValues.


        :param end_heat_setpoint: The end_heat_setpoint of this ThermostatChangeableValues.  # noqa: E501
        :type: float
        """

        self._end_heat_setpoint = end_heat_setpoint

    @property
    def end_cool_setpoint(self):
        """Gets the end_cool_setpoint of this ThermostatChangeableValues.  # noqa: E501


        :return: The end_cool_setpoint of this ThermostatChangeableValues.  # noqa: E501
        :rtype: float
        """
        return self._end_cool_setpoint

    @end_cool_setpoint.setter
    def end_cool_setpoint(self, end_cool_setpoint):
        """Sets the end_cool_setpoint of this ThermostatChangeableValues.


        :param end_cool_setpoint: The end_cool_setpoint of this ThermostatChangeableValues.  # noqa: E501
        :type: float
        """

        self._end_cool_setpoint = end_cool_setpoint

    @property
    def heat_cool_mode(self):
        """Gets the heat_cool_mode of this ThermostatChangeableValues.  # noqa: E501


        :return: The heat_cool_mode of this ThermostatChangeableValues.  # noqa: E501
        :rtype: str
        """
        return self._heat_cool_mode

    @heat_cool_mode.setter
    def heat_cool_mode(self, heat_cool_mode):
        """Sets the heat_cool_mode of this ThermostatChangeableValues.


        :param heat_cool_mode: The heat_cool_mode of this ThermostatChangeableValues.  # noqa: E501
        :type: str
        """

        self._heat_cool_mode = heat_cool_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ThermostatChangeableValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
