# coding: utf-8

"""
    Honeywell Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ThermostatSensor(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'device_id': 'str',
        'group_id': 'int',
        'rooms': 'list[ThermostatSensorRooms]'
    }

    attribute_map = {
        'device_id': 'deviceId',
        'group_id': 'groupId',
        'rooms': 'rooms'
    }

    def __init__(self, device_id=None, group_id=None, rooms=None):  # noqa: E501
        """ThermostatSensor - a model defined in OpenAPI"""  # noqa: E501

        self._device_id = None
        self._group_id = None
        self._rooms = None
        self.discriminator = None

        if device_id is not None:
            self.device_id = device_id
        if group_id is not None:
            self.group_id = group_id
        if rooms is not None:
            self.rooms = rooms

    @property
    def device_id(self):
        """Gets the device_id of this ThermostatSensor.  # noqa: E501


        :return: The device_id of this ThermostatSensor.  # noqa: E501
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this ThermostatSensor.


        :param device_id: The device_id of this ThermostatSensor.  # noqa: E501
        :type: str
        """

        self._device_id = device_id

    @property
    def group_id(self):
        """Gets the group_id of this ThermostatSensor.  # noqa: E501


        :return: The group_id of this ThermostatSensor.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this ThermostatSensor.


        :param group_id: The group_id of this ThermostatSensor.  # noqa: E501
        :type: int
        """

        self._group_id = group_id

    @property
    def rooms(self):
        """Gets the rooms of this ThermostatSensor.  # noqa: E501


        :return: The rooms of this ThermostatSensor.  # noqa: E501
        :rtype: list[ThermostatSensorRooms]
        """
        return self._rooms

    @rooms.setter
    def rooms(self, rooms):
        """Sets the rooms of this ThermostatSensor.


        :param rooms: The rooms of this ThermostatSensor.  # noqa: E501
        :type: list[ThermostatSensorRooms]
        """

        self._rooms = rooms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ThermostatSensor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
