# coding: utf-8

"""
    Honeywell Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ThermostatScheduleCapabilities(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'available_schedule_types': 'list[str]',
        'schedulable_fan': 'bool'
    }

    attribute_map = {
        'available_schedule_types': 'availableScheduleTypes',
        'schedulable_fan': 'schedulableFan'
    }

    def __init__(self, available_schedule_types=None, schedulable_fan=None):  # noqa: E501
        """ThermostatScheduleCapabilities - a model defined in OpenAPI"""  # noqa: E501

        self._available_schedule_types = None
        self._schedulable_fan = None
        self.discriminator = None

        if available_schedule_types is not None:
            self.available_schedule_types = available_schedule_types
        if schedulable_fan is not None:
            self.schedulable_fan = schedulable_fan

    @property
    def available_schedule_types(self):
        """Gets the available_schedule_types of this ThermostatScheduleCapabilities.  # noqa: E501


        :return: The available_schedule_types of this ThermostatScheduleCapabilities.  # noqa: E501
        :rtype: list[str]
        """
        return self._available_schedule_types

    @available_schedule_types.setter
    def available_schedule_types(self, available_schedule_types):
        """Sets the available_schedule_types of this ThermostatScheduleCapabilities.


        :param available_schedule_types: The available_schedule_types of this ThermostatScheduleCapabilities.  # noqa: E501
        :type: list[str]
        """

        self._available_schedule_types = available_schedule_types

    @property
    def schedulable_fan(self):
        """Gets the schedulable_fan of this ThermostatScheduleCapabilities.  # noqa: E501


        :return: The schedulable_fan of this ThermostatScheduleCapabilities.  # noqa: E501
        :rtype: bool
        """
        return self._schedulable_fan

    @schedulable_fan.setter
    def schedulable_fan(self, schedulable_fan):
        """Sets the schedulable_fan of this ThermostatScheduleCapabilities.


        :param schedulable_fan: The schedulable_fan of this ThermostatScheduleCapabilities.  # noqa: E501
        :type: bool
        """

        self._schedulable_fan = schedulable_fan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ThermostatScheduleCapabilities):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
