# coding: utf-8

"""
    Honeywell Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class UpdatePriority(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'current_priority': 'UpdatePriorityCurrentPriority'
    }

    attribute_map = {
        'current_priority': 'currentPriority'
    }

    def __init__(self, current_priority=None):  # noqa: E501
        """UpdatePriority - a model defined in OpenAPI"""  # noqa: E501

        self._current_priority = None
        self.discriminator = None

        if current_priority is not None:
            self.current_priority = current_priority

    @property
    def current_priority(self):
        """Gets the current_priority of this UpdatePriority.  # noqa: E501


        :return: The current_priority of this UpdatePriority.  # noqa: E501
        :rtype: UpdatePriorityCurrentPriority
        """
        return self._current_priority

    @current_priority.setter
    def current_priority(self, current_priority):
        """Sets the current_priority of this UpdatePriority.


        :param current_priority: The current_priority of this UpdatePriority.  # noqa: E501
        :type: UpdatePriorityCurrentPriority
        """

        self._current_priority = current_priority

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdatePriority):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
