# coding: utf-8

"""
    Honeywell Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class UpdatePriorityCurrentPriority(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'priority_type': 'str',
        'selected_rooms': 'list[int]'
    }

    attribute_map = {
        'priority_type': 'priorityType',
        'selected_rooms': 'selectedRooms'
    }

    def __init__(self, priority_type=None, selected_rooms=None):  # noqa: E501
        """UpdatePriorityCurrentPriority - a model defined in OpenAPI"""  # noqa: E501

        self._priority_type = None
        self._selected_rooms = None
        self.discriminator = None

        if priority_type is not None:
            self.priority_type = priority_type
        if selected_rooms is not None:
            self.selected_rooms = selected_rooms

    @property
    def priority_type(self):
        """Gets the priority_type of this UpdatePriorityCurrentPriority.  # noqa: E501


        :return: The priority_type of this UpdatePriorityCurrentPriority.  # noqa: E501
        :rtype: str
        """
        return self._priority_type

    @priority_type.setter
    def priority_type(self, priority_type):
        """Sets the priority_type of this UpdatePriorityCurrentPriority.


        :param priority_type: The priority_type of this UpdatePriorityCurrentPriority.  # noqa: E501
        :type: str
        """
        allowed_values = ["PickARoom", "FollowMe", "WholeHouse"]  # noqa: E501
        if priority_type not in allowed_values:
            raise ValueError(
                "Invalid value for `priority_type` ({0}), must be one of {1}"  # noqa: E501
                .format(priority_type, allowed_values)
            )

        self._priority_type = priority_type

    @property
    def selected_rooms(self):
        """Gets the selected_rooms of this UpdatePriorityCurrentPriority.  # noqa: E501


        :return: The selected_rooms of this UpdatePriorityCurrentPriority.  # noqa: E501
        :rtype: list[int]
        """
        return self._selected_rooms

    @selected_rooms.setter
    def selected_rooms(self, selected_rooms):
        """Sets the selected_rooms of this UpdatePriorityCurrentPriority.


        :param selected_rooms: The selected_rooms of this UpdatePriorityCurrentPriority.  # noqa: E501
        :type: list[int]
        """

        self._selected_rooms = selected_rooms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdatePriorityCurrentPriority):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
